general {
    colors = true
    color_good = "#1688f0"
    color_degraded = "#e6cd69"
    color_bad = "#ff0043"
    interval = 2
}

order += "cpu_usage"
order += "memory"
order += "disk /"
order += "wireless _first_"
order += "ethernet _first_"
order += "volume master"
order += "battery all"
order += "tztime local"

cpu_usage {
    format = "󰍛 %usage"
}

memory {
    format = "󰘚 %used"
    threshold_degraded = "10%"
    format_degraded = "󰘚 %available"
}

disk "/" {
    format = "󰋊 %avail"
}

wireless _first_ {
    format_up = "󰤨 %essid (%quality)"
    format_down = "󰤮 "
}

ethernet _first_ {
    format_up = "󰈀 %ip"
    format_down = ""
}

volume master {
    format = "󰕾 %volume"
    format_muted = "󰝟 %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

battery all {
    format = "%status %percentage"
    format_down = "󰂎"
    status_chr = "󰂄"
    status_bat = "󰁹"
    status_unk = "󰂑"
    status_full = "󰁹"
    last_full_capacity = true
    integer_battery_capacity = true
    low_threshold = 15
    threshold_type = percentage
}

tztime local {
    format = "󰥔 %a %b %d, %I:%M %p"
}
